### ISSUE TITLE
Implement Stream.WriteTo with custom offset

### ISSUE THREAD

**Issue by priverop** [SceneGate/Yarhl#73]
Right now this would be impossible because WriteTo [reinitializes position to 0](https://github.com/SceneGate/Yarhl/blob/master/src/Yarhl/IO/DataStream.cs#L479):

```csharp
string tempFile = Path.GetTempFileName();

DataReader reader = new DataReader(node.Stream);
reader.Stream.Position = 4;
reader.Stream.WriteTo(tempFile);
```
And we are forced to use this:

```csharp
using (var substream = new DataStream(node.Stream, 4, node.Stream.Length - 4)) {
    substream.WriteTo(tempFile);
}
```

It would be nice to have a `Stream.WriteTo(file, offset)`

**Comment by pleonex** [comment]
My concerns is that `WriteTo(file, offset)` seems that we are going to write the current full string to the output file starting at the destination offset, instead of starting to read our stream at the position. We also should consider the use case of writing from the current position. Maybe we should need another method name. Not sure yet.

**Comment by priverop** [comment]
After discussing our best approach would be to use `WriteTo(start: 4, path: file)`.

**Comment by pleonex** [comment]
We could also have a `WriteSegmentTo(start: 4, length: 80, path: file)` and `WriteSegmentTo(start: 4, path: file)`. I think this new method name could be easier to understand the behavior (writing a segment of the stream). There should be another overload with same signatures but writing to `DataStream` to be consistent with `WriteTo`.

**Comment by Megaflan** [comment]
Shouldn't be otherwise? I mean, the `WriteTo `function with the `path; file` string parameter calls the `WriteTo `function with a ```
using (var stream = DataStreamFactory.FromFile(fileOut, FileOpenMode.Write)) {
                WriteTo(stream);
            }.
```
A `WriteSegmentTo(start: 4, length: 80, path: file)` should be first a `WriteSegmentTo(start: 4, length: 80, DataStream: stream)` and then, the `WriteSegmentTo(start: 4, length: 80, path: file)`, it should call ```
using (var stream = DataStreamFactory.FromFile(fileOut, FileOpenMode.Write)) {
                WriteSegmentTo(start: 4, length: 80, DataStream: stream);
            }.
```

**Comment by Megaflan** [comment]
Shouldn't be otherwise? I mean, the `WriteTo` function with the `path; file` string parameter calls the `WriteTo` function with a
```
using (var stream = DataStreamFactory.FromFile(fileOut, FileOpenMode.Write)) {
                WriteTo(stream);
            }.
```
A `WriteSegmentTo(start: 4, length: 80, path: file)` should be first a `WriteSegmentTo(start: 4, length: 80, DataStream: stream)` and then, the `WriteSegmentTo(start: 4, length: 80, path: file)`, it should be
```
using (var stream = DataStreamFactory.FromFile(fileOut, FileOpenMode.Write)) {
                WriteSegmentTo(start: 4, length: 80, DataStream: stream);
            }.
```
