### ISSUE TITLE
Change DataStream.WriteTo(DataStream stream) to DataStream.Clone(DataStream stream)

### ISSUE THREAD

**Issue by Darkmet98** [SceneGate/Yarhl#95]
**Is your feature request related to a problem? Please describe.**
WriteTo(Stream) is very confusing, because the original function is write the stream to a file, not a another stream.

**Describe the solution you'd like**
Change the name to Clone.

**Comment by pleonex** [comment]
`WriteTo(Stream)` is actually writing the content of the `DataStream` into an existing `Stream`. It is not cloning because if that `Stream` had previous content, the bytes from `DataStream` will be appended. It's not creating either a new `Stream`. It's just another way to `WriteTo`, another overload.
